### ISSUE TITLE
KeyError: 'unexpected key "base.0.weight" in state_dict'

### ISSUE THREAD

**Issue by charan223** [amdegroot/ssd.pytorch#106]
(virtualenv) [charan@cuda-server ssd.pytorch]$ python eval.py 
	Traceback (most recent call last):
	  File "eval.py", line 423, in <module>
	    net.load_state_dict(torch.load(args.trained_model))
	  File "/home/charan/anaconda2/envs/virtualenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
	    .format(name))
	KeyError: 'unexpected key "base.0.weight" in state_dict'

Got this error when tried to evaluate on trained VOC 2007 model (ssd_300_voc07.pkl)

**Comment by amdegroot** [comment]
I'll look into it, but I was just about to deprecate the v1 version (older version of the model) which is what that weight file is based on.  Is there a specific reason you were trying to use the v1 model weights or will the other weights listed in the README work for your use case? 

SSD300 v2 trained on VOC0712 (newest PyTorch version)
https://s3.amazonaws.com/amdegroot-models/ssd300_mAP_77.43_v2.pth
SSD300 v2 trained on VOC0712 (original Caffe version)
https://s3.amazonaws.com/amdegroot-models/ssd_300_VOC0712.pth

**Comment by charan223** [comment]
I am working on a project connected to ssd using only VOC 2007, so I need weights file trained on VOC2007.

**Comment by amdegroot** [comment]
Ah okay.  Try replacing ssd.py with this older [version](https://gist.github.com/amdegroot/6de05667b86e59c882bbc09362e6559e).

**Comment by charan223** [comment]
that ssd.py is not working....getting below error...
in ssd.py, In line 5, data folder doesnt have c9_2, pool6

**Comment by celdeldel** [comment]
have you finally solved the issue?
