### ISSUE TITLE
Illegal memory access / Spike in GPU memory usage

### ISSUE THREAD

**Issue by lemairecarl** [amdegroot/ssd.pytorch#113]
I can't use a batch size larger than 2, because when launching train.py, GPU memory usage spikes to around 10 GB. If I try batch_size=4, I get a "out of memory" error.

Also, I get random `RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generated/../THCReduceAll.cuh:334`, as it already been reported by others.

It may be coming from the version of PyTorch. Are you compatible with the last version of PyTorch? If not, please indicate in the README which version you support.

I tried with 0.12, without luck. Now I'm trying with 0.2, still no luck. And I also get this warning:
`UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.`

**Comment by lemairecarl** [comment]
It was due to PyTorch trying to use my old Nvidia GT 710, in addition to my TITAN. Sorry bout that.

**Comment by abdo-ameen** [comment]
can you please tell which Nvidia GPU model you were using? and what was the batch size that didn't consume the whole RAM and give the "out of memory" error?
