### ISSUE TITLE
Could you share your instances_trainval35k.json.zip file ?

### ISSUE THREAD

**Issue by FostorHUNT** [amdegroot/ssd.pytorch#123]

**Comment by ellisbrown** [comment]
here they are on S3: https://s3.amazonaws.com/amdegroot-datasets/instances_trainval35k.json.zip

We also have created a script to form the trainval35k dataset for you on the COCO branch.  We hope to merge these into master soon
https://github.com/amdegroot/ssd.pytorch/blob/coco/data/scripts/COCO2014.sh

**Comment by FostorHUNT** [comment]
Sorry @ellisbrown , I knew this S3 link before adding the issue. Unfortunately, I got 'access denied' response when using the command line
`curl -LO  https://s3.amazonaws.com/amdegroot-datasets/instances_trainval35k.json.zip`
The file I got is:
`<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>A4DF808B97BA75E5</RequestId><HostId>L88xkRSVyyagBYgVHKb860AkBPFdH1RcYZK1kfOaJWILmVe3YLeFEUyU9v6xPvbiOuL05yJUUUo=</HostId></Error>`

**Comment by amdegroot** [comment]
Sorry about that, I still need to make the bucket public.  

This [link](https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip?dl=0) should work.  It's the same annotations, just taken from Ross Girshick's [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn/tree/master/data) repo, which is where I pulled ours from.
