### ISSUE TITLE
Where did you get the original Caffe weights file -- ssd_300_VOC0712.pth?

### ISSUE THREAD

**Issue by xiaozhi2015** [amdegroot/ssd.pytorch#128]
@amdegroot   What I got from original Caffe is VGG_VOC0712_SSD_300x300_iter_120000.caffemodel file.
So where did you get the original Caffe weights file -- ssd_300_VOC0712.pth?

**Comment by hengck23** [comment]
i verified that 'ssd_300_VOC0712.pth' is from 'VGG_VOC0712_SSD_300x300_iter_120000.caffemodel'.
I made my own caffe to pytorch converter and have the exact same results for both files.

**Comment by kirIn0305** [comment]
I want to convert .pth file from 'VGG_VOC0712_SSD_300x300_iter_120000.caffemodel.
Do you change only the weights of first layer from rgb to bgr, and the other layers unchanged?

**Comment by gjm441** [comment]
> i verified that 'ssd_300_VOC0712.pth' is from 'VGG_VOC0712_SSD_300x300_iter_120000.caffemodel'.
> I made my own caffe to pytorch converter and have the exact same results for both files.

@hengck23 ,hi,can you share your scripts for converting ssd caffemodel to pth?Great thanks!
