### ISSUE TITLE
Wrong use of Pytorch function dim()

### ISSUE THREAD

**Issue by abdo-eldesokey** [amdegroot/ssd.pytorch#130]
In detection.py, line 49
`if scores.dim() == 0:
      continue`
The function dim() returns 1 even if the tensor is empty, so the execution continues and I get an error because nms() function gets empty tensors.
Instead using .size(0) will give the desired behavior.

**Comment by jiachen0212** [comment]
yes you are right...   and i changed the scores.dim()==0 as scores.size(0)==0, but when i run eval.py   i still got a bug......like this:
  File "eval.py", line 395, in test_net
    boxes = dets[:, 1:]
how can i deal with it?

**Comment by zhaohui-yang** [comment]
> yes you are right... and i changed the scores.dim()==0 as scores.size(0)==0, but when i run eval.py i still got a bug......like this:
> File "eval.py", line 395, in test_net
> boxes = dets[:, 1:]
> how can i deal with it?

line 397,  modify dim() to size(0)
