### ISSUE TITLE
some questions in utils.augmentations.py

### ISSUE THREAD

**Issue by yingdiLee** [amdegroot/ssd.pytorch#133]
in line 9:
def intersect(box_a, box_b):
    max_xy = np.minimum(box_a[:, 2:], box_b[2:])
    min_xy = np.maximum(box_a[:, :2], box_b[:2])
    inter = np.clip((max_xy - min_xy), a_min=0, a_max=np.inf)
    return inter[:, 0] * inter[:, 1]
what is the meaning of box_a and box_b? dose it means four coordinates of bounding box？
（xmin，ymin，xmax，ymax） . And what exactly does max_xy and min_xy mean? I am a little confused here.

**Comment by FostorHUNT** [comment]
> what is the meaning of box_a and box_b?
Yes, these are the two boxes you want to get the IoU of them.

> dose it means four coordinates of bounding box？（xmin，ymin，xmax，ymax）
Yes, you are right.

> what exactly does max_xy and min_xy mean? I am a little confused here.
That are four coordinates of the new bounding box which is the intersection of box_a and box_b.
