### ISSUE TITLE
Error while modified to train my own dataset

### ISSUE THREAD

**Issue by TinaLiuCV** [amdegroot/ssd.pytorch#17]
Hi, I recently modify your code to train my own dataset.
Basically I did following changes:
1.Change the classes, num_classes
2. Change the dataset path
3. Change the RGB mean value of the dataset

Then I ran the modified train.py and encounter with an error:
CUDA_LAUNCH_BLOCKING=1 python train_button.py 
Loading base network...
Initializing weights...
Loading Dataset...
Training SSD on button
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
/b/wheel/pytorch-src/torch/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THCUNN/generic/ClassNLLCriterion.cu line=83 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train_button.py", line 204, in <module>
    train()
  File "train_button.py", line 160, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/deep-server/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/deep-server/Documents/Jingya/ssd.pytorch/modules/multibox_loss.py", line 110, in forward
    loss_c = F.cross_entropy(conf_p, targets_weighted, size_average=False)
  File "/home/deep-server/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/functional.py", line 509, in cross_entropy
    return nll_loss(log_softmax(input), target, weight, size_average)
  File "/home/deep-server/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/functional.py", line 477, in nll_loss
    return f(input, target)
  File "/home/deep-server/.pyenv/versions/anaconda3-4.2.0/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 41, in forward
    output, *self.additional_args)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /b/wheel/pytorch-src/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:83

Can you please help me with the possible reason for the error?
It should related to  the line of loss_c = F.cross_entropy(conf_p, targets_weighted, size_average=False) 
But I don't understand how it would go wrong.
Thank you in advance.

**Comment by amdegroot** [comment]
Hi, I apologize for getting back to you so late.  That error means that you are giving `F.cross_entropy()` an invalid class index.  If you are using a "background" label make sure that is handled properly because currently my code treats the 0 index as a "background" label.  If I had to guess you are most likely giving it an index that is 1 higher than it should be due to the fact that we add 1 to each index to account for the "background" class at index 0 [here](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/box_utils.py#L112).  Let me know if you have any more issues.  I will be adding some code to make it easier for custom datasets very soon (school is ending this week so I should have more time)!

**Comment by meetshah1995** [comment]
@amdegroot - Any update on custom dataset loader?

If you're a little busy, could you point to the places to look into ( that treat the background class from Pascal VOC point of view) so that I can make a custom dataloader ( with other relevant changes) and send a PR.

**Comment by quinnliu4real** [comment]
@amdegroot 

Hi, what do you mean by '1 higher than it should be'?   Suppose I only have 1 class to be trained then what the label index should be?    0 or 1?   
Thx.

**Comment by pyaf** [comment]
@quinnliu4real Hey, did you figure this out? I think the label should be 1, right?

**Comment by Weacera** [comment]
@TinaLiuCV How the dataset mean?And how to get the value in someother datasets?
