### ISSUE TITLE
About : y = net(x) ,Not enough values to unpack (expected 2, got 0) ?

### ISSUE THREAD

**Issue by door5719** [amdegroot/ssd.pytorch#171]
Python 3.5.2 |Anaconda     4.2.0 (64-bit)|
torch                                   0.4.0
torchvision                          0.2.1
when i run the program test.py,there is some mistake as follow:
-----------------------------------------------------------------------------------------------------------
C:\Users\Anaconda3\python.exe D:/pytorch_ssd/test.py
D:\pytorch_ssd\ssd.py:34: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
D:\pytorch_ssd\layers\modules\l2norm.py:17: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.weight,self.gamma)
Finished loading model!
Testing image 1/4952....
Traceback (most recent call last):
  File "D:/pytorch_ssd/test.py", line 97, in <module>
    test_voc()
  File "D:/pytorch_ssd/test.py", line 94, in test_voc
    thresh=args.visual_threshold)
  File "D:/pytorch_ssd/test.py", line 56, in test_net
    y = net(x)      # forward pass
  File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\pytorch_ssd\ssd.py", line 103, in forward
    self.priors.type(type(x.data))                  # default boxes
  File "D:\pytorch_ssd\layers\functions\detection.py", line 54, in forward
    ids, count = nms(boxes, scores, self.nms_thresh, self.top_k)
ValueError: not enough values to unpack (expected 2, got 0)

Process finished with exit code 1
---------------------------------------------------------------------------------------------------------
why ?

**Comment by door5719** [comment]
i'm so sorry about it because the reason is torch 0.4

**Comment by yingdiLee** [comment]
I have meet the same problem, how do you slove it?

**Comment by ShaniGam** [comment]
@yingdiLee see (https://github.com/amdegroot/ssd.pytorch/issues/154#issuecomment-384856547)
