### ISSUE TITLE
PriorBox: the box is out of the image

### ISSUE THREAD

**Issue by AceCoooool** [amdegroot/ssd.pytorch#18]
The prior_box.py using the version v2: every box can be described as (x, y, w, h) instead of the v1 (x1, y1, x2, y2)
 using the clamp_(max=1, min=0) will cause the 'bottom box' out of the image. For example: the output[-5, :] is  0.8333, 0.8333, 0.5020, 1.000。 so the x2 and y2 is out of the image. I am not sure whether it will cause the accuracy, maybe can modify it like the v1.  (maybe it will not be a problem)

**Comment by AceCoooool** [comment]
And I am also confusing : in the decode function using the variance, but there is no "variance operation" in the prior_box.

**Comment by amdegroot** [comment]
Hi, I apologize for taking so long to get back to you.  Finishing up school this week and then will be able to spend more time on this.  I will get back to you on the first question ASAP, but I want to give you a good response and I don't have time at the moment.  As for your second question, the `decode` function (which is only used at test time) includes the variance because the variance is encoded in the `encode` function at training time.

**Comment by jeong-tae** [comment]
Hi, is there a any answer about this issue? the output box is out of image!

**Comment by amdegroot** [comment]
@jeong-tae Can you please provide a specific example?  I personally have not run into this issue.

**Comment by jeong-tae** [comment]
@amdegroot same issue with the @acecoooool
the prior boxes has a out of image coords such as 0.8 0.8 0.5 1.0. is it normal in v2?
i got out of image boxes with my dataset, so i track the values. and i found out the boxes are little bit skewed to bottom right(label matched with skewed one, i dont know why). for example, label cxcy has 0.3 0.3, but after encode it returns 0.5 0.5. but w,h are quite similar bw encode decode. also gt and pred

**Comment by jeong-tae** [comment]
@amdegroot Here is more specific example for trace this. The truths loc was [0.34, 0.17, 0.74, 1.0] before the encode. To do encode, match first and then encode it. Matched prior box was [0.53, 0.32, 0.38, 0.76]. (i think the match part have problem. w, h seems no problem but cxcy has!). The result of encoded loc was [2.7, 8.85, -3.0, 1.13]. To ensure this process is right, i tried decode encoded loc. it returns [0.58, 0.13, 0.77, 1.07].

**Comment by jeong-tae** [comment]
Hello. I think this is only problem of my code. When i get the matches, i revised some codes and it may occur this issue(i didn't know this was modified on my code). Let me check. if still have problem, let you know. Sorry for the bothering you.
