### ISSUE TITLE
TypeError: 'module' object is not subscriptable

### ISSUE THREAD

**Issue by isalirezag** [amdegroot/ssd.pytorch#189]
I am doing the demo and face this issue
![image](https://user-images.githubusercontent.com/12434910/42130237-01a1d546-7cad-11e8-9516-575b93239222.png)

**Comment by isalirezag** [comment]
The problem was because of pytorch 0.4... :/

**Comment by rinawhale** [comment]
Hi , I meet the same problem, which version of Pytorch should I use?

**Comment by isalirezag** [comment]
0.3.1 works fine
