### ISSUE TITLE
A question about  the L2Norm.py code

### ISSUE THREAD

**Issue by fanser** [amdegroot/ssd.pytorch#19]
Hello, I don't understand why you calculate out = weight*x before return out and not return the x straightly.Could you tell me the reason? 
thx~~   :）

 def forward(self, x):
        norm = x.pow(2).sum(1).sqrt()+self.eps
        x/=norm.expand_as(x)
       out = self.weight.unsqueeze(0).unsqueeze(2).unsqueeze(3).expand_as(x) * x          <= here
        return out

**Comment by amdegroot** [comment]
Hi! The reasoning behind this stems from the fact that convolution 4_3 learns to recognize features at a different scale so the norm at each location of the feature map is initially scaled to 20 and then during backprop the scale is learned by means of the weight matrix that you're referring to in our code.  This is explained in the Experiment Results section of the SSD paper [here.](https://arxiv.org/pdf/1512.02325.pdf)

**Comment by isalirezag** [comment]
@fanser In L2Norm function, what scale is used for? i dont get the meaning of it used in this function :/
