### ISSUE TITLE
regarding permute and contiguous

### ISSUE THREAD

**Issue by isalirezag** [amdegroot/ssd.pytorch#195]
can someone tell me what             `loc.append(l(x).permute(0, 2, 3, 1).contiguous())`
does?
I dont understand what permute and contiguous does, and how they wrk

**Comment by pierluigiferrari** [comment]
Not to be a dick, but there is really no need to open an issue for a question like that. You can just read the PyTorch documentation, or you can do a Google search and find this question asked on StackOverflow like [here](https://stackoverflow.com/questions/48915810/pytorch-contiguous), or you can write a quick toy example and visualize for yourself what these methods do.

**Comment by isalirezag** [comment]
@pierluigiferrari I sorry about being so naive. i guess you are right

**Comment by chungyau97** [comment]
@isalirezag I know how permute and contiguous work in coding. But I don't understand why they want to change the shape of it. Can you kindly explain it to me?
