### ISSUE TITLE
Error when run test.py

### ISSUE THREAD

**Issue by DragonBornHD** [amdegroot/ssd.pytorch#2]
Hi, there is a problem hope you can help me, thank you.

  File "/home/hd/ssd.pytorch/data/voc.py", line 222
    gts.append([label, *(int(bb.text) - 1 for bb in bbox)])
                                 ^
SyntaxError: invalid syntax

This error occur when I run the test.py. Thank you again.
^ under the *

**Comment by amdegroot** [comment]
Hey, I can't reproduce that on my computer and can't really think of why that would be an issue off the top of my head.  I will look into this more after class and get back to you, sorry about that.

**Comment by DragonBornHD** [comment]
It's my bad. I find my python version is 2.7......sorry to disturb

**Comment by amdegroot** [comment]
No worries at all! We are working to support python 2.7, so maybe check back in the future.
