### ISSUE TITLE
Number of priors wrong on Multi-GPU mode

### ISSUE THREAD

**Issue by DeanChan** [amdegroot/ssd.pytorch#20]
Hi there~

The PriorBox would encounter an error on multi-GPU mode. For example, when running on  one GPU, the output size would be:
 - size(loc_data) = (16, 8732, 4)
 - size(conf_data) = (16, 8732, 21)
 - size(priors) = (8732, 4)

This is correct. But When running on 2 GPUs, the size of priors would be (17464, 4) and (26196, 4) on 3 GPUs, while the sizes of loc_data and conf_data remain the same as they are on 1 GPU. 

ps. I found this bug when applying `net = torch.nn.DataParallel(net).cuda()` in [train.py](https://github.com/amdegroot/ssd.pytorch/blob/master/train.py) 

Hope to see the solution.

Thanks.

**Comment by amdegroot** [comment]
Hi, yes thank you for mentioning that.  This is another item I need to add to my to do list.  Currently, I am working on perfecting the training phase on a single GPU and then will work on adding that feature.  If you come up with a solution before I get around to it feel free to send a PR!

**Comment by alexkoltun** [comment]
AFAIK it was resolved in the latest version

**Comment by MrWanter** [comment]
how to use the multi gpu mode?

**Comment by sonukiller** [comment]
In the training script line no. 99 use,
`net = torch.nn.DataParallel(ssd_net, device_ids=[0])`
