### ISSUE TITLE
annoying bug

### ISSUE THREAD

**Issue by isalirezag** [amdegroot/ssd.pytorch#207]
No matter what you do if you did not have downloaded the datasets you will get this f***cking error...
`FileNotFoundError: [Errno 2] No such file or directory: '/home/alireza/data/coco/coco_labels.txt'`
Why do i need to see this error when i wanna try the demo......

**Comment by abhiksark** [comment]
How did you solve this?

**Comment by srihithalwala** [comment]
change COCO_ROOT = osp.join(HOME, 'ssd.pytorch/data/coco')
to
COCO_ROOT = osp.join(HOME, 'ssd.pytorch/data/')
