### ISSUE TITLE
Outputs are always the same.

### ISSUE THREAD

**Issue by chenxinyang123** [amdegroot/ssd.pytorch#213]
I train it on my own data, then I find that any picture will get same result. Does anyone see this problem before?

**Comment by detectRecog** [comment]
hello, did you figure out what's the problem?

**Comment by zhao181** [comment]
how did you figure it out? I met the same problem. I trained the kitti dataset. The outputs for different images are almost the same.

**Comment by chenxinyang123** [comment]
The error in my code is the dataloader using my own dataset is wrong. Maybe you can check the dataloader, especially the value of bounding box.
