### ISSUE TITLE
NaN values at Multibox encoding

### ISSUE THREAD

**Issue by andfoy** [amdegroot/ssd.pytorch#22]
I've tried to implement my own dataset detector, however at training time, the localization loss is NaN due to negative values present on ``g_wh``  [layers/box_utils.py#L137](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/box_utils.py#L137), I don't know if this error is related to the format of the bounding boxes or if it's related to the output of the SSD model. 

I would like to know if am I doing something wrong while loading the dataset or if the error is related to a bug on the base implementation.

**Comment by andfoy** [comment]
I was loading incorrectly the bounding boxes

**Comment by meetshah1995** [comment]
@andfoy - What was your fix? 

Were you getting this same error: 

```
THCudaCheck FAIL file=/b/wheel/pytorch-src/torch/lib/THC/generic/THCTensorMath.cu line=226 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train_cars.py", line 232, in <module>
    train()
  File "train_cars.py", line 184, in train
    loss_l, loss_c = criterion(out, targets)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mshah/code/ssd.pytorch/layers/modules/multibox_loss.py", line 70, in forward
    match(self.threshold,truths,defaults,self.variance,labels,loc_t,conf_t,idx)
  File "/home/mshah/code/ssd.pytorch/layers/box_utils.py", line 107, in match
    loc = encode(matches, priors, variances)
  File "/home/mshah/code/ssd.pytorch/layers/box_utils.py", line 133, in encode
    return torch.cat([g_cxcy, g_wh], 1)  # [num_priors,4]
RuntimeError: cuda runtime error (59) : device-side assert triggered at /b/wheel/pytorch-src/torch/lib/THC/generic/THCTensorMath.cu:226
```

**Comment by yxchng** [comment]
@andfoy  @meetshah1995 I am also getting the same error as meetshah1995. Have you guys solve the problem?

**Comment by andfoy** [comment]
I forgot to load the bounding box annotations scaled by the image dimensions

**Comment by yxchng** [comment]
So the code cannot be used straight away? It must be corrected?

**Comment by andfoy** [comment]
No, you need to transform your annotations (Bounding boxes) into [x0/w, y0/h, x1/w, y1/h], where (x0, y0) and (x1, y1) are the coordinates of the upper left and lower right corners of the bounding box. h and w are the image height and width, respectively

**Comment by yxchng** [comment]
Isn't AnnotationTransform doing that?

**Comment by andfoy** [comment]
I think those transforms are loading the Pascal VOC XML data representation and then it transforms it to the representation described above. Anyway, if you are dealing with your own dataset, I would recommend to write your own loading routines based on the Pascal ones and then test them on the model. It is important that the bounding box annotations are on the correct format :-)

**Comment by Cadene** [comment]
Indeed, the easiest way by far is to convert your own dataset format into the Pascal VOC one (in a first instance).

**Comment by yxchng** [comment]
@andfoy @Cadene I am just trying to train Pascal and not my own dataset. So using AnnotationTransform should do the job? But I am still getting NaN. Can I know what I should change?

**Comment by Cadene** [comment]
@yxchng I am sorry, I don't know why you're getting NaN. Training on Pascal VOC 0712 was straightforward to me (I did not change anything). I am running the last version of pytorch available on conda. Did you try to reinstall pytorch?

**Comment by yxchng** [comment]
@Cadene It works with python3 but not with python2. I wonder why. Also, can I know how does your losses look like during training?

**Comment by niaoyu** [comment]
@yxchng Hi, I just faced the same problems just like you in python2. Have you got some conclusions about the NaN loss error?

**Comment by niaoyu** [comment]
@yxchng  oh i see, the reason is '/'  all the bounding box params will be 0; modify just like:
cur_pt = cur_pt / width if i % 2 == 0 else  cur_pt / height
=>
cur_pt = 1.0 * cur_pt / width if i % 2 == 0 else 1.0 * cur_pt / height
