### ISSUE TITLE
When run the train.py, how many iterations will go?

### ISSUE THREAD

**Issue by hailey94** [amdegroot/ssd.pytorch#225]
in the config.py, voc = max iter is 12000, coco = max iter is 40000
i haven't changed anything from the default setting and run the train.py
and i saw the message in the terminal that traning SSD on VOC dataset.
but now i'm in iter 17930 and it still goes on.
is this means that this ssd works on COCO? or do i have to set up something else for VOC?

how many iterations did you saw, when you just run the train.py with default setting?

**Comment by hailey94** [comment]
sorry i miscount the zeros,,,, it was 120000 and 400000 ;D

**Comment by ztianlin** [comment]
Hi~how many iterations and how long does it take for you to train on coco?
