### ISSUE TITLE
[question] Where can I calculate the MAP?

### ISSUE THREAD

**Issue by oarriaga** [amdegroot/ssd.pytorch#23]
Hello @amdegroot,
thank you for making your code available. I am currently working in the ssd_keras port. However, we are missing the MAP score and I saw that you have already calculated yours. Do you think you could pin-point which code did you use to evaluate your SSD port.

Also I saw that you are missing the data_augmentation part. Maybe you could take a look [here](https://github.com/oarriaga/single_shot_multibox_detector/blob/master/src/image_generator.py). It is a python generator, it is currently missing the crop transformation but it has helped me reach a better loss. 

Thank you!

**Comment by kimdon20** [comment]
Has this MAP score calculation portion been updated ?

**Comment by oarriaga** [comment]
Hi @kimdon20,
No I still have not figured out (also because I stopped searching for it) where to calculate the MAP score, but it could still be very helpful :) (@amdegroot)

**Comment by xwjabc** [comment]
+1. Hope for some mAP calculation code.

**Comment by amdegroot** [comment]
Hey guys, just posted the mAP calculation code in eval.py.  I have also posted a link to some pytorch weights that achieve a slightly higher mAP than the original caffe weights now that data augmentation and the fully training from scratch pipeline is complete.  Sorry this took so long.
