### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by LAWSSSS** [amdegroot/ssd.pytorch#236]
I DON'T KNOW WHY AND HOW TO FIX IT.

**Comment by Brozhao** [comment]
I have the same error.

**Comment by pxjx** [comment]
I have the same error, too. I have spent two days solving it. Maybe the format of your  dataset is wrong. My dataset has 9 images whose format is .JPG while others are .jpg, so I correct them to .jpg, and then I overcome this error.

**Comment by LAWSSSS** [comment]
> I have the same error, too. I have spent two days solving it. Maybe the format of your dataset is wrong. My dataset has 9 images whose format is .JPG while others are .jpg, so I correct them to .jpg, and then I overcome this error.

Thanks. I'll give it a try. Best regards.

**Comment by adityac8** [comment]
You have to make sure that your images are in the directory structure as VOC.
Check `voc0712.py` in `VOCDetection`
`self._imgpath = osp.join('%s', 'JPEGImages', '%s.jpg')`
You can also change this as per need.

**Comment by Icecream-blue-sky** [comment]
Just change coco.py:
from: img=cv2.imread(osp.join(self.root,path))
to:img=cv2.imread(path)
