### ISSUE TITLE
eval.py Error [ ValueError: not enough values to unpack (expected 2, got 0) ]

### ISSUE THREAD

**Issue by MakeToast** [amdegroot/ssd.pytorch#251]
../ssd.pytorch/layers/functions/detection.py", line 54, in forward
    ids, count = nms(boxes, scores, self.nms_thresh, self.top_k)
ValueError: not enough values to unpack (expected 2, got 0)

What does that mean?
How to solve that problem?

**Comment by MakeToast** [comment]
reference : https://github.com/amdegroot/ssd.pytorch/issues/154

I changed the code as follows and worked for me.
In detection.py of line 49
from

if scores.dim() == 0:
    continue
to

if scores.size(0) == 0:
    continue

**Comment by CodeForWuyu** [comment]
@MakeToast  Thanks, it worked

**Comment by yuvrajkhanna** [comment]
I am having the same problem while trying demo i am getting this same error i did changes as above still issue persists what should I do??

**Comment by CodeForWuyu** [comment]
@yuvrajkhanna #154 may help

**Comment by hello-ljs** [comment]
fuck this bug

**Comment by BITTER799** [comment]
@MakeToast  Thanks a lot！

**Comment by AjayTiwari2661** [comment]
@MakeToast, i tried your solution reference #154 but the following error is being displayed for every frame and the detection is not up to the mark. I couldn't understand this, could you explain please.
..\torch\csrc\autograd\python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function) ..\torch\csrc\autograd\python_function.cpp:648: UserWarning: Legacy autograd function object was called twice. You will probably get incorrect gradients from this computation, as the saved tensors from the second invocation will clobber the saved tensors from the first invocation. Please consider rewriting your autograd function in the modern style; for information on the new format, please see: https://pytorch.org/docs/stable/notes/extending.html#extending-torch-autograd
