### ISSUE TITLE
demo on video

### ISSUE THREAD

**Issue by sophia-wright-blue** [amdegroot/ssd.pytorch#255]
thank you for releasing this repo. could you advise me on the changes to be made to the 'demo/live.py' script to do a demo on an mp4 video file, instead of a live feed.

thanks,

**Comment by lvboodvl** [comment]
you can try some changes from line44 as below:

    # stream = WebcamVideoStream(src=0).start()  # default camera
    stream = cv2.VideoCapture('/root/video9.mp4') # mp4 video file
    
    time.sleep(1.0)
    # start fps timer
    # loop over frames from the video file stream
    while True:
        # grab next frame
        # frame = stream.read()
        ret, frame = stream.read() # new code
        key = cv2.waitKey(1) & 0xFF

        # update FPS counter
        fps.update()
        frame = predict(frame)

        # keybindings for display
        if key == ord('p'):  # pause
            while True:
                key2 = cv2.waitKey(1) or 0xff
                cv2.imshow('frame', frame)
                if key2 == ord('p'):  # resume
                    break
        cv2.imshow('frame', frame)
        if key == 27:  # exit
            break

**Comment by sophia-wright-blue** [comment]
thank you so much!

**Comment by zhaoedf** [comment]
does this demo perform in cuda?
