### ISSUE TITLE
how to obtain weiliu89 weights

### ISSUE THREAD

**Issue by kimdon20** [amdegroot/ssd.pytorch#27]
I was wondering how I could obtain weiliu89 weights to validate 77.2%. I have changed some parts of the code and just want to validate if it is still reproducible. Thanks

**Comment by amdegroot** [comment]
A download link for obtaining the original caffe weights is listed on the Readme.

**Comment by kimdon20** [comment]
hi @amdegroot would that be the link to original caffe code which contains a caffe version of the weights?? I was wondering which MAP code you used to produce the results in the README, I just would like to confirm with mine also ! Thanks :)

**Comment by amdegroot** [comment]
Hi! That link was the link to the original caffe weights, correct.  I have now posted the mAP eval code in eval.py.
