### ISSUE TITLE
No such file or directory: 'test.txt'

### ISSUE THREAD

**Issue by JingpengSun** [amdegroot/ssd.pytorch#272]
When I run eval.py I can get the results file, as following(I just use 3 images to test the code)
Finished loading model!
F:\Research\Pytorch-SSD-master\ssd.py:100: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  self.softmax(conf.view(-1, self.num_classes)),  # conf preds
im_detect: 1/3 1.819s
im_detect: 2/3 3.539s
im_detect: 3/3 1.817s
Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "F:/Research/Pytorch-SSD-master/eval.py", line 424, in <module>
    thresh=args.confidence_threshold)
  File "F:/Research/Pytorch-SSD-master/eval.py", line 401, in test_net
    evaluate_detections(all_boxes, output_dir, dataset)
  File "F:/Research/Pytorch-SSD-master/eval.py", line 406, in evaluate_detections
    do_python_eval(output_dir)
  File "F:/Research/Pytorch-SSD-master/eval.py", line 163, in do_python_eval
    ovthresh=0.5, use_07_metric=use_07_metric)
  File "F:/Research/Pytorch-SSD-master/eval.py", line 250, in voc_eval
    with open(imagesetfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

but, finally, it gives FileNotFoundError: No such file or directory: 'test.txt'
I have no idea about the 'test.txt' because I have already a 'test.txt' in path'~\VOC2007\ImageSets\Main\'
Have anyone met this? Thanks!

**Comment by JingpengSun** [comment]
I figure it out, it's path problem.

**Comment by BerryLJ** [comment]
> 
> 
> I figure it out, it's path problem.
Hello, how did you solve your problem？

**Comment by sxyxf66** [comment]
How do you fix it ?

**Comment by sxyxf66** [comment]
> I figure it out, it's path problem.

I have the same problem.  Do you know how to fix it? thanks
