### ISSUE TITLE
Error when I training my dataset

### ISSUE THREAD

**Issue by ThorPham** [amdegroot/ssd.pytorch#286]
I have error : 
 File "train.py", line 186, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/thangtran/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/thangtran/ThangTran/DungPham_Checked/ssd_voc/ssd.pytorch-master/layers/modules/multibox_loss.py", line 97, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
RuntimeError: copy_if failed to synchronize: device-side assert triggered
(base) thangtran@rpa:~/ThangTran/DungPham_Checked/ssd_voc/ssd.pytorch-mas
 Can you help me fix it

**Comment by eng100200** [comment]
@ThorPham hello!

**Comment by ThorPham** [comment]
@lianxxx  i fixed this error:
My dataset has 1 class and 2k image for training. I want to custom VGG to CNN with light weight.

**Comment by eng100200** [comment]
@ThorPham  2k images, have you made your own dataset,, what kind of class you have ,,,human or any other object?

**Comment by guiw629** [comment]
the loss function request more than 1 class.

**Comment by krxat** [comment]
@ThorPham Did you solve the issue??
If yes can you please explain the steps took to train on 1 class with your own dataset?
Thanks.

**Comment by ThorPham** [comment]
@cypherix  you can make dataset same format VOC.

**Comment by krxat** [comment]
@ThorPham How many iterations did you train for and did it produce good accuracy??

**Comment by rw1995** [comment]
how do you fix it?i meet the same problem

**Comment by eng100200** [comment]
@rw1995  what is the problem?

**Comment by JuAobo** [comment]
set the 'num_classes' in config to 2. You should include the bkg class

**Comment by lironghua318** [comment]
> set the 'num_classes' in config to 2. You should include the bkg class

谢谢，解决了我的问题
