### ISSUE TITLE
error:Dimension out of range

### ISSUE THREAD

**Issue by DragonBornHD** [amdegroot/ssd.pytorch#3]
When I run test.py, the sentence “y = net(x)” is error:
RuntimeError: dimension out of range - got 1 but the tensor is only 1D

Change:

'--cuda', default=True

thank you for help.

**Comment by amdegroot** [comment]
Sorry I'm on vacation this weekend and not at my computer.  Can you paste the full error message?  Also make sure you have the latest version of the repo, you might want to do a git pull if you haven't recently.

**Comment by DragonBornHD** [comment]
The error as follow:

Finished loading model!
Testing image 1/2510....
Traceback (most recent call last):
  File "test.py", line 105, in <module>
    test_net(args.save_folder, net, args.cuda, valset, base_transform(net.size,(104,117,123)), args.top_k, thresh=args.confidence_threshold)
  File "test.py", line 56, in test_net
    y = net(x)      # forward pass
  File "/home/hd/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hd/ssd.pytorch/ssd.py", line 107, in forward
    self.priors                                      # default boxes
  File "/home/hd/ssd.pytorch/functions/detection.py", line 59, in forward
    self.nms_threshold, self.keep_top_k)
  File "/home/hd/ssd.pytorch/box_utils.py", line 256, in nms
    return torch.cat((scores[keep[:count]],boxes[keep[:count]]),1),count
RuntimeError: dimension out of range - got 1 but the tensor is only 1D

**Comment by amdegroot** [comment]
Hey sorry for leaving you hanging. I was pretty confused about this issue because it just randomly showed up but I found out its because of a recent PyTorch update you can find [here](https://github.com/pytorch/pytorch/releases/tag/v0.1.11).  It turns out torch.cat used to support catting along non-existent dimensions, but 3 days ago that was disallowed.  So I'll fix that right now
