### ISSUE TITLE
Error not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by amdramsey** [amdegroot/ssd.pytorch#301]
# The code
import torch
import cv2
from torch.autograd import Variable
from data import BaseTransform, VOC_CLASSES as labelmap
from ssd import build_ssd

def detect(frame, net, transform):
    height, width = frame.shape[:2]
    frame_t = transform(frame)[0]
    x = torch.from_numpy(frame_t).permute(2,0,1) # From RBG To GRB
    x = Variable(x.unsqueeze(0))
    y = net(x)
    detections = y.data # [batch, number_of_calsses, number_of_occurrence, (score, x0, y0, x1, y1)]
    scale = torch.Tensor([width,height,width,height])
    for i in range(detections.size(1)):
        j = 0
        while detections[0, i, j, 0] >= 0.6:
            pt = (detections[0, i, j, 1:] * scale).numpy()
            cv2.rectangle(frame, int(pt[0]), int(pt[1]), int(pt[2]), int(pt[3]), (255,0,0), 2)
            cv2.putText(frame, labelmap[i-1], int(pt[0]), int(pt[1]), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,255,255), 2, cv2.LINE_AA)
            j+=1
    return frame

net = build_ssd('test')
net.load_state_dict(torch.load('ssd300_mAP_77.43_v2.pth', map_location=lambda storage, loc:storage))

transform = BaseTransform(net.size, (104/256.0, 117/256.0, 123/256.0))

video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read() # detect(frame, net.eval(), transform)
    cv2.imshow('Video', detect(frame, net.eval(), transform))
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()
# And it gives me error "not enough values to unpack (expected 2, got 0)"

**Comment by muchuanyun** [comment]
Please refer to issue #154

**Comment by amdegroot** [comment]
thanks, resolved.

**Comment by PoojanPanchal** [comment]
hey, what changes you made that resolved your problem??
can you please upload ur corrected code?

**Comment by sarth23** [comment]
@amdramsey can you tell what changes did you do in your code to make it work properly.!!Thanks in advance.!!
