### ISSUE TITLE
train.py RuntimeError

### ISSUE THREAD

**Issue by anitaweng** [amdegroot/ssd.pytorch#307]
I an new to pytorch and I cannot solve this error even if I try every solutions in issues.
Can anyone help me?
I use :
cuda 10
pytorch 1.0.1
python 3.5
batch-size 32
lr 1e-3

And I have changed line 182 in train.py into 
loss = (loss_l + loss_c)/1000.0

Also changed dim() into size(0)

Change 
        N = num_pos.data.sum()
        loss_l /= N
        loss_c/ = N
into 
        N = num_pos.data.sum().double()
        loss_l = loss_l.double()
        loss_c = loss_c.double()

in multibox_loss.py

Below are my error messages:

iter 290 || Loss: 2.8487 || Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train()
  File "train.py", line 181, in train
    loss_l, loss_c = criterion(out, targets)
  File "/home/anita/anaconda3/envs/python3.5/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anita/ssd.pytorch/layers/modules/multibox_loss.py", line 74, in forward
    loc_t, conf_t, idx)
  File "/home/anita/ssd.pytorch/layers/box_utils.py", line 106, in match
    best_truth_idx[best_prior_idx[j]] = j
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by AIprogrammer** [comment]
hi, have you solved it yet?

**Comment by AIprogrammer** [comment]
> I an new to pytorch and I cannot solve this error even if I try every solutions in issues.
> Can anyone help me?
> I use :
> cuda 10
> pytorch 1.0.1
> python 3.5
> batch-size 32
> lr 1e-3
> 
> And I have changed line 182 in train.py into
> loss = (loss_l + loss_c)/1000.0
> 
> Also changed dim() into size(0)
> 
> Change
> N = num_pos.data.sum()
> loss_l /= N
> loss_c/ = N
> into
> N = num_pos.data.sum().double()
> loss_l = loss_l.double()
> loss_c = loss_c.double()
> 
> in multibox_loss.py
> 
> Below are my error messages:
> 
> iter 290 || Loss: 2.8487 || Traceback (most recent call last):
> File "train.py", line 258, in 
> train()
> File "train.py", line 181, in train
> loss_l, loss_c = criterion(out, targets)
> File "/home/anita/anaconda3/envs/python3.5/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/anita/ssd.pytorch/layers/modules/multibox_loss.py", line 74, in forward
> loc_t, conf_t, idx)
> File "/home/anita/ssd.pytorch/layers/box_utils.py", line 106, in match
> best_truth_idx[best_prior_idx[j]] = j
> RuntimeError: CUDA error: an illegal memory access was encountered

hi, have you solved it yet?

**Comment by anitaweng** [comment]
I used Cuda 9.0 instead and installed the corresponding pytorch again.

**Comment by AIprogrammer** [comment]
> I used Cuda 9.0 instead and installed the corresponding pytorch again.

Do you know the reason of it ? Only due to the version?

**Comment by AIprogrammer** [comment]
> > I used Cuda 9.0 instead and installed the corresponding pytorch again.
> 
> Do you know the reason of it ? Only due to the version?

Why the error did not occur at the beginning, but after some iterations? Appreciate your reply if you know.

**Comment by anitaweng** [comment]
Sorry, I don't know why. I want to know the reason, too.😕

**Comment by anitaweng** [comment]
Sorry, I don't know why. I want to know the reason, too.😕
