### ISSUE TITLE
Can anyone help me with a dataloader(voc0712.py)

### ISSUE THREAD

**Issue by krxat** [amdegroot/ssd.pytorch#318]
I am trying to train a model with one class - pedestrian or person. I tried to work around on the voc0712.py but it didn't help and created a lot of errors. 
I tried changing the conf file with 1 class and changed the VOC_CLASSES to pedestrian only and it didn't work. Also, I tried doing some other stuff and play around with the code but giving out multiple errors.
My tree would look like this :
.
    ├── Annotations
    ├── ImageSets
    │   └── Main
    └── JPEGImages
If there is anyone who can help me, it would be appreciated. Thanks.

**Comment by cypherix** [comment]
>
