### ISSUE TITLE
tensors are on different GPUs

### ISSUE THREAD

**Issue by DragonBornHD** [amdegroot/ssd.pytorch#32]
I run the demo, return 'tensors are on different GPSs' , but I have only one GPU. 
The demo was run successfully with CPU.
Can you put the process of using the GPU to release it?
Thank you very much!

**Comment by alexkoltun** [comment]
Most likely that the net is not on GPU, try adding the following, just after weight loading:
if torch.cuda.is_available():
    net = net.cuda()

**Comment by DragonBornHD** [comment]
I tried this way, another error occurred:

TypeError: mul received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.cuda.FloatTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)



I added the 'net = net.cuda()' after 'net.load_state_dict(torch.load(trained_model))' , and 'x = x.cuda()' after 'x = Variable(x.unsqueeze(0))' . 
Thank you.

**Comment by alexkoltun** [comment]
I see.. I think setting the default tensor to be cuda might solve it, try to put the following somewhere before model loading:
```python
if torch.cuda.is_available():
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
```

**Comment by DragonBornHD** [comment]
That's doesn't work, same problem.

**Comment by alexkoltun** [comment]
Did you restart the kernel? 

I tested with the following change on a GPU machine and it works:

```python
if torch.cuda.is_available():
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
net = build_ssd('test', 300, 21)    # initialize SSD
net.load_weights('../weights/ssd300_mAP_77.43_v2.pth')
if torch.cuda.is_available():
    net = net.cuda()
```

**Comment by DragonBornHD** [comment]
Yes it works！
`torch.set_default_tensor_type('torch.cuda.FloatTensor')` Should before `net = build_ssd('test', 300, 21)` 
Thank you very much !!

**Comment by DonghoonPark12** [comment]
@alexkoltun 
I'm sorry but, when I train my network on gpu by below code,
```python
if torch.cuda.is_available():
    net = net.cuda()
```

Why there is another need when I'm training for example in train.py
```python
        if args.cuda:
            images = images.cuda()
            targets = [ann.cuda() for ann in targets]
        else:
            images = images
            targets = [ann for ann in targets]
```
Is there also diffenrence between below two line??
```python
images = images.cuda()
# and
images = images
````

Thanks ahead.
