### ISSUE TITLE
One problem of demo.py with my dataset

### ISSUE THREAD

**Issue by sxyxf66** [amdegroot/ssd.pytorch#346]
when I use my trained model in the demo.py, it has the error:

RuntimeError: Error(s) in loading state_dict for SSD:
	size mismatch for conf.0.weight: copying a param with shape torch.Size([8, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 512, 3, 3]).
	size mismatch for conf.0.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for conf.1.weight: copying a param with shape torch.Size([12, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 1024, 3, 3]).
	size mismatch for conf.1.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.2.weight: copying a param with shape torch.Size([12, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 512, 3, 3]).
	size mismatch for conf.2.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.3.weight: copying a param with shape torch.Size([12, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([126, 256, 3, 3]).
	size mismatch for conf.3.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([126]).
	size mismatch for conf.4.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
	size mismatch for conf.4.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([84]).
	size mismatch for conf.5.weight: copying a param with shape torch.Size([8, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([84, 256, 3, 3]).
	size mismatch for conf.5.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current mode

Do you know how to fix it?

**Comment by sxyxf66** [comment]
Have fixed:   net = build_ssd('test', 300, 2)    # initialize SSD

**Comment by izmevid** [comment]
@sxyxf66 I am having the same issue. Could you please help me with what to do to avoid it? I am not quite understanding what you mean with the comment on your fix.

![IMG_20200819_171047](https://user-images.githubusercontent.com/22737812/90653103-1288e580-e23f-11ea-8316-237b44f9abfa.jpg)

I am using this https://github.com/dusty-nv/jetson-inference.

**Comment by Suncheng2019** [comment]
> Have fixed: net = build_ssd('test', 300, 2) # initialize SSD
2代表自己数据集的数量（包括背景一类），修改了就不会与权重出现mismatch，感谢！
