### ISSUE TITLE
Do the most models ignore difficulte instance in training and testing in PASCAL VOC competition?

### ISSUE THREAD

**Issue by acgtyrant** [amdegroot/ssd.pytorch#35]
I do not read the source code about py-faster-rcnn while its readiblity is poor. I noticed that you dose not keep difficulte instances in training and testing in PASCAL VOC. So tell me please, [the most models](http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=4) ignore difficulte instance in training and testing in PASCAL VOC competition too, right? Thank you!

**Comment by amdegroot** [comment]
Yes that is correct.  The actual competition may have included difficult instances, but the original ssd and the original faster-Rcnn papers report results without the "difficult" instances.
