### ISSUE TITLE
How can I find the Average Precision and Average Recall from the eval.py file? 

### ISSUE THREAD

**Issue by AtriSaxena** [amdegroot/ssd.pytorch#352]
I want to find the Average Recall and Precision values. I have tried, printing these value [Code link](https://github.com/amdegroot/ssd.pytorch/blob/5b0b77faa955c1917b0c710d770739ba8fbff9b7/eval.py#L351)
        `rec = tp / float(npos)
        prec = tp / np.maximum(tp + fp, np.finfo(np.float64).eps)`

But it is printing long list of values which i am not able to get.

**Comment by jiawen7777** [comment]
I meet the same problem, have you solved it?  Thank you very much

**Comment by AtriSaxena** [comment]
I have solved but it was long time ago. I don't remember but tell me more about the problem you are getting? I have used custom data in VOC format. 
Can you show me error you are getting?

**Comment by wallcuber** [comment]
I have the same question. The rec and prec is so long. How did you deal with this？
![image](https://user-images.githubusercontent.com/58249279/79678570-8d110c80-822f-11ea-9a25-95b8e8f06aca.png)


> I have solved but it was long time ago. I don't remember but tell me more about the problem you are getting? I have used custom data in VOC format.
> Can you show me error you are getting?

**Comment by wallcuber** [comment]
> I have solved but it was long time ago. I don't remember but tell me more about the problem you are getting? I have used custom data in VOC format.
> Can you show me error you are getting?

Does rec[-1] and prec[-1] are the final average Recall and Precision ?

**Comment by AtriSaxena** [comment]
After this [Link](https://github.com/amdegroot/ssd.pytorch/blob/5b0b77faa955c1917b0c710d770739ba8fbff9b7/eval.py#L176) I have added this code. 

`rec += [rec]
prec += [prec]`

And also define rec = [] and prec = []

Than you can print 
`print('Average Recall = {:.4f}'.format(np.mean(rec)))
 print('Average Precision = {:.4f}'.format(np.mean(prec)))`


```for i, cls in enumerate(labelmap):
        filename = get_voc_results_file_template(set_type, cls)

        rec, prec, ap = voc_eval(
           filename, annopath, imgsetpath.format(set_type), cls, cachedir,
           ovthresh=0.5, use_07_metric=use_07_metric)
        aps += [ap]
        rec += [rec]
        prec += [prec]
        print('AP for {} = {:.4f}'.format(cls, ap))
        with open(os.path.join(output_dir, cls + '_pr.pkl'), 'wb') as f:
            pickle.dump({'rec': rec, 'prec': prec, 'ap': ap}, f)
    print('Mean AP = {:.4f}'.format(np.mean(aps)))
    print('Average Recall = {:.4f}'.format(np.mean(rec)))
    print('Average Precision = {:.4f}'.format(np.mean(prec)))```

The whole loop will be something like this. 
If you are using Custom dataset than you need more changes. 
If this solves tells me.

**Comment by jiawen7777** [comment]
wow！thank you! It works!



---Original---

**Comment by jiawen7777** [comment]
I think I might miss your reply before
I just saw the reply this morning, Sorry

**Comment by AtriSaxena** [comment]
Yeah, I replied last night. I was little busy. Great, it helped you.

**Comment by zyx961022** [comment]
ValueError: non-broadcastable output operand with shape (11725,) doesn't match the broadcast shape (1,11725)
![image](https://user-images.githubusercontent.com/48480546/86534763-9a27c880-bf0d-11ea-8aa5-bb7c6f5ab550.png)

Why do I report this error and how to solve it? please help me， thank you！

**Comment by shirui-japina** [comment]
> ValueError: non-broadcastable output operand with shape (11725,) doesn't match the broadcast shape (1,11725)
> ![image](https://user-images.githubusercontent.com/48480546/86534763-9a27c880-bf0d-11ea-8aa5-bb7c6f5ab550.png)
> 
> Why do I report this error and how to solve it? please help me， thank you！

The same.

**Comment by ghost** [comment]
> ValueError: non-broadcastable output operand with shape (11725,) doesn't match the broadcast shape (1,11725)
> ![image](https://user-images.githubusercontent.com/48480546/86534763-9a27c880-bf0d-11ea-8aa5-bb7c6f5ab550.png)
> 
> Why do I report this error and how to solve it? please help me， thank you！

Have you solved the problem? I encountered the same problem as you.
Then I referred `aps += [ap]` and @AtriSaxena 's comment, I added these codes:
```
...
recs = []
precs = []
...
        ...
        recs += [rec]
        precs += [prec]
        ...
    ...
    print('Average Recall = {:.4f}'.format(np.mean(recs)))
    print('Average Precision = {:.4f}'.format(np.mean(precs)))
    ...
```
This will work, but I’m not sure if it’s right. What do you think?

**Comment by poorguy2001** [comment]
> ValueError：形状为 (11725,) 的不可广播输出操作数与广播形状 (1,11725) 不匹配 ![图像](https://user-images.githubusercontent.com/48480546/86534763-9a27c880-bf0d-11ea-8aa5-bb7c6f5ab550.png)
> 
> 为什么我会报这个错误，如何解决？请帮帮我，谢谢！

def do_python_eval(output_dir='output', use_07=True):
    cachedir = os.path.join(devkit_path, 'annotations_cache')
    aps = []
    recs = []
    precs = []
    # The PASCAL VOC metric changed in 2010
    use_07_metric = use_07
    print('VOC07 metric? ' + ('Yes' if use_07_metric else 'No'))
    if not os.path.isdir(output_dir):
        os.makedirs(output_dir, exist_ok=True)
    for i, cls in enumerate(labelmap):
        filename = get_voc_results_file_template(set_type, cls)
        rec, prec, ap = voc_eval(
           filename, annopath, imgsetpath.format(set_type), cls, cachedir,
           ovthresh=0.5, use_07_metric=use_07_metric)
        aps.append(ap)
        recs.append(np.mean(rec))
        precs.append(np.mean(prec))
        print('AP for {} = {:.4f}'.format(cls, ap))
        with open(os.path.join(output_dir, cls + '_pr.pkl'), 'wb') as f:
            pickle.dump({'rec': rec, 'prec': prec, 'ap': ap}, f)
    print('Mean AP = {:.4f}'.format(np.mean(aps)))
    print('Average Recall = {:.4f}'.format(np.mean(recs)))
    print('Average Precision = {:.4f}'.format(np.mean(precs)))

**Comment by zyx961022** [comment]
你标注的数据标签有错误 或者是你设置的标签种类和你自己数据集的标签种类不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月5日(星期三) 晚上9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [amdegroot/ssd.pytorch] How can I find the Average Precision and Average Recall from the eval.py file?  (#352)














  
ValueError：形状为 (11725,) 的不可广播输出操作数与广播形状 (1,11725) 不匹配 
 
为什么我会报这个错误，如何解决？请帮帮我，谢谢！
  
def do_python_eval(output_dir='output', use_07=True):
 cachedir = os.path.join(devkit_path, 'annotations_cache')
 aps = []
 recs = []
 precs = []
 # The PASCAL VOC metric changed in 2010
 use_07_metric = use_07
 print('VOC07 metric? ' + ('Yes' if use_07_metric else 'No'))
 if not os.path.isdir(output_dir):
 os.makedirs(output_dir, exist_ok=True)
 for i, cls in enumerate(labelmap):
 filename = get_voc_results_file_template(set_type, cls)
 rec, prec, ap = voc_eval(
 filename, annopath, imgsetpath.format(set_type), cls, cachedir,
 ovthresh=0.5, use_07_metric=use_07_metric)
 aps.append(ap)
 recs.append(np.mean(rec))
 precs.append(np.mean(prec))
 print('AP for {} = {:.4f}'.format(cls, ap))
 with open(os.path.join(output_dir, cls + '_pr.pkl'), 'wb') as f:
 pickle.dump({'rec': rec, 'prec': prec, 'ap': ap}, f)
 print('Mean AP = {:.4f}'.format(np.mean(aps)))
 print('Average Recall = {:.4f}'.format(np.mean(recs)))
 print('Average Precision = {:.4f}'.format(np.mean(precs)))
