### ISSUE TITLE
Can you follow PEP 8?

### ISSUE THREAD

**Issue by acgtyrant** [amdegroot/ssd.pytorch#36]
Better Style be beneficial to all.

**Comment by amdegroot** [comment]
I will try to update the style when I get back from vacation, but is there anything in particular that's unreadable due to a lack of PEP 8 styling?

**Comment by acgtyrant** [comment]
As far as I know, no. I may report when I find something in particular that's unreadable in the future.

**Comment by amdegroot** [comment]
Okay, thanks for pointing this out. there are a few more pressing additional features we would like to add at the moment (custom dataset training compatibility, ssd 512, etc...), but we will take this into account when we get back from vacation.
