### ISSUE TITLE
Demo and Evaluation Detection

### ISSUE THREAD

**Issue by herleeyandi** [amdegroot/ssd.pytorch#42]
Hello finally I can run your code. But I don't know why the MAP is 0.0 for all. When I am using demo.ipynb I can't plot the bounding box, but the detection has been completed.
![image](https://user-images.githubusercontent.com/2309538/28541351-46613fec-70eb-11e7-8e0f-223a65c64b46.png)
![image](https://user-images.githubusercontent.com/2309538/28541367-59e431be-70eb-11e7-9a6e-627c133425e9.png)
![image](https://user-images.githubusercontent.com/2309538/28541399-7186cf34-70eb-11e7-92d1-c8e5db18c537.png)

How to fix this?
-Thank you-

**Comment by herleeyandi** [comment]
New Fact!
Coordinate result is same, so the size of the box is 0!
How to fix this?
![image](https://user-images.githubusercontent.com/2309538/28542149-df2cec4c-70ed-11e7-9edc-2c22921ff3e2.png)

**Comment by amdegroot** [comment]
I can't reproduce these issues.  Have you changed any of the original code?

**Comment by herleeyandi** [comment]
I try to porting your code to Python 2.7. I make 2 replacement:
1) In `ssd.py`
![image](https://user-images.githubusercontent.com/2309538/28917574-b2287aa8-7878-11e7-9468-a553e8103b8c.png)

2) in `./layers/modules/l2norm.py`
![image](https://user-images.githubusercontent.com/2309538/28917615-cf889c68-7878-11e7-8198-f0ed90e17a31.png)

I think it should not have any problem with the box. Or is there any problem if I just change 2 of it? When will you release for python 2.7?
-Thank you-

**Comment by orangehdc** [comment]
@herleeyandi  I have the same problem!
 I am using Python2.7 and finally got mAP=0. I don't know what's wrong with my code.

**Comment by orangehdc** [comment]
@herleeyandi  I have found a bug. We should change the code in prior_box.py where s_k and s_k_prime were set to zero. That's why the prior boxes are empty. Just do a simple convertion like 
`float(self.min_size[k])`
and the result will get bigger. However, I just got mAP = 0.16. It's still too low

**Comment by amdegroot** [comment]
Hey guys, sorry I haven't spent a lot of time on 2.7 integration.  Hopefully I will find some free time in the next couple of days and I will look into it.  If you do find a solution however or manage to integrate it with 2.7 completely, feel free to submit a PR or send me an email!

**Comment by herleeyandi** [comment]
@orangehdc Thank you for your information, I will try it later. Yes I also try to port it to python 2.7 . Now I am reading paper and also seeing the code. Hopefully I can find the bug. I will post here and tell you @amdegroot if I have successfully resolve some errors. I also have some repositories that need attention over 2 months, sorry for my late reply -_- .

**Comment by jackiechen0708** [comment]
@orangehdc  I doesn't convert int to float.
Instead I use Python3 division 
`from __future__ import division`
and the mAP reach to 
![image](https://user-images.githubusercontent.com/12592618/34346326-63490f1c-ea31-11e7-9728-794a2bb5d8e5.png)
