### ISSUE TITLE
COCO performance

### ISSUE THREAD

**Issue by Wuziyi616** [amdegroot/ssd.pytorch#422]
Has anyone trained and tested this ssd on coco dataset? I got a MAP=0.213 which is 0.02 less than the original paper (0.232). So I wonder what's you guys performance? Thanks!

**Comment by lesonly** [comment]
> Has anyone trained and tested this ssd on coco dataset? I got a MAP=0.213 which is 0.02 less than the original paper (0.232). So I wonder what's you guys performance? Thanks!

Hi，Could you provide the code to generate the result file.Thanks a lot! My email is 23006592@qq.com

**Comment by lesonly** [comment]
> Has anyone trained and tested this ssd on coco dataset? I got a MAP=0.213 which is 0.02 less than the original paper (0.232). So I wonder what's you guys performance? Thanks!

Hello, Ziyi Wu, Happy New Year! I got a map = 0.04, I think it may be that I use the wrong code to generate the result file. Could you send me the code to generate the result file? This question has puzzled me for a long time. Thank you very much!

**Comment by lesonly** [comment]
> Has anyone trained and tested this ssd on coco dataset? I got a MAP=0.213 which is 0.02 less than the original paper (0.232). So I wonder what's you guys performance? Thanks!

Hello, Ziyi Wu, Happy New Year! I got a map = 0.04, I think it may be that I use the wrong code to generate the result file. Could you send me the code to generate the result file? This question has puzzled me for a long time. Thank you very much!My email is 23006592@qq.com

**Comment by Wuziyi616** [comment]
@lesonly Hi! Sorry for replying late. Actually this repo doesn't contain the code for testing on COCO as you can see. I adopt the code from another SSD repo (https://github.com/lufficc/SSD) and modified it to suit the input and output. I don't think you can use my code directly after I send it to you... Really sorry about that.
Honestly speaking, I recommend you to just shift to that repo if you really want a COCO result. That repo is also well written, and contains all the coco-evaluation codes you need. When I modified the code from this repo to be suitable for coco testing, it just took me a lot of time to debug.

**Comment by lesonly** [comment]
Thank you for your enthusiasm reply!I am watching the&nbsp; SSD repo (https://github.com/lufficc/SSD),but i can't find&nbsp;the code which to generate the result file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ziyi Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月1日(星期三) 晚上7:48
收件人:&nbsp;"amdegroot/ssd.pytorch"<ssd.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"朱"<23006592@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [amdegroot/ssd.pytorch] COCO performance (#422)




@lesonly Hi! Sorry for replying late. Actually this repo doesn't contain the code for testing on COCO as you can see. I adopt the code from another SSD repo (https://github.com/lufficc/SSD) and modified it to suit the input and output. I don't think you can use my code directly after I send it to you... Really sorry about that.
 Honestly speaking, I recommend you to just shift to that repo if you really want a COCO result. That repo is also well written, and contains all the coco-evaluation codes you need. When I modified the code from this repo to be suitable for coco testing, it just took me a lot of time to debug.

**Comment by lesonly** [comment]
> @lesonly Hi! Sorry for replying late. Actually this repo doesn't contain the code for testing on COCO as you can see. I adopt the code from another SSD repo (https://github.com/lufficc/SSD) and modified it to suit the input and output. I don't think you can use my code directly after I send it to you... Really sorry about that.
> Honestly speaking, I recommend you to just shift to that repo if you really want a COCO result. That repo is also well written, and contains all the coco-evaluation codes you need. When I modified the code from this repo to be suitable for coco testing, it just took me a lot of time to debug.

Thank you for your enthusiasm reply!I am watching the SSD repo (https://github.com/lufficc/SSD),but i can't find the code which to generate the result file.

**Comment by Wuziyi616** [comment]
It's actually in SSD/ssd/data/datasets/evaluation/coco/__init__.py

**Comment by lesonly** [comment]
> It's actually in SSD/ssd/data/datasets/evaluation/coco/**init**.py

Thank you  for your warm reply and help again. I will study it carefully

**Comment by JiHaoqina** [comment]
@Wuziyi616 Hi, I

**Comment by JiHaoqina** [comment]
@Wuziyi616 Hi, I trained this ssd on COCO train2017 and tested the model on val2017，and I got the mAP 0.240，which is a little higher than the original paper (0.232). My result is as follow:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.411
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.248
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.059
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.259
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.405
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.235
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.355
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.384
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.588

**Comment by lesonly** [comment]
> @Wuziyi616 Hi, I trained this ssd on COCO train2017 and tested the model on val2017，and I got the mAP 0.240，which is a little higher than the original paper (0.232). My result is as follow:
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.240
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.411
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.248
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.059
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.259
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.405
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.235
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.355
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.384
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.588

You're great!Could you send me the code to generate the result file? This question has puzzled me for a long time. Thank you very much!My email is 23006592@qq.com

**Comment by lesonly** [comment]
> @Wuziyi616 Hi, I trained this ssd on COCO train2017 and tested the model on val2017，and I got the mAP 0.240，which is a little higher than the original paper (0.232). My result is as follow:
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.240
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.411
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.248
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.059
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.259
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.405
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.235
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.355
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.384
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.588

@JiHaoqina You're great! I got a map = 21.8, which is same to Wuziyi616.I think it may be that I use the wrong code to generate the result file. Could you send me the code to generate the result file? or exchange it with each other. Thank you very much!My email is 23006592@qq.com

**Comment by rebeen** [comment]
can anyone share the  evaluation on coco dataset please

**Comment by rebeen** [comment]
> @Wuziyi616 Hi, I trained this ssd on COCO train2017 and tested the model on val2017，and I got the mAP 0.240，which is a little higher than the original paper (0.232). My result is as follow:
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.240
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.411
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.248
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.059
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.259
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.405
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.235
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.355
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.384
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.131
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.588

can you please share your evaluated code since only training is available so it could be really helpful to share your testing code 
thank you

**Comment by Wuziyi616** [comment]
Hello everyone! I've overcome this issue recently and [here](https://drive.google.com/open?id=1Zw3rURyAzkB0EUP_U5KFsHi5qLYRfX6O) is the evaluation code and coco dataset class I used for this. There are two things I want to notice you:

- The code is used for COCO 2017! So please download the 2017 Train, Val, Train/Val Annotations from http://cocodataset.org/#download. COCO 2014 is not supported by my dataset

- If you want to train with the dataset provided in coco2017.py, just use:
  train_set = COCODetection(root='path/to/data', image_sets=[('2017', 'train')], preproc=your_data_preprocessing_method, target_transform=COCOAnnotationTransform)

 Hope this will help you!

**Comment by ovidov** [comment]
> Hello everyone! I've overcome this issue recently and [here](https://drive.google.com/open?id=1Zw3rURyAzkB0EUP_U5KFsHi5qLYRfX6O) is the evaluation code and coco dataset class I used for this. There are two things I want to notice you:
> 
> * The code is used for COCO 2017! So please download the 2017 Train, Val, Train/Val Annotations from http://cocodataset.org/#download. COCO 2014 is not supported by my dataset
> * If you want to train with the dataset provided in coco2017.py, just use:
>   train_set = COCODetection(root='path/to/data', image_sets=[('2017', 'train')], preproc=your_data_preprocessing_method, target_transform=COCOAnnotationTransform)
> 
> Hope this will help you!

> Hello everyone! I've overcome this issue recently and [here](https://drive.google.com/open?id=1Zw3rURyAzkB0EUP_U5KFsHi5qLYRfX6O) is the evaluation code and coco dataset class I used for this. There are two things I want to notice you:
> 
> * The code is used for COCO 2017! So please download the 2017 Train, Val, Train/Val Annotations from http://cocodataset.org/#download. COCO 2014 is not supported by my dataset
> * If you want to train with the dataset provided in coco2017.py, just use:
>   train_set = COCODetection(root='path/to/data', image_sets=[('2017', 'train')], preproc=your_data_preprocessing_method, target_transform=COCOAnnotationTransform)
> 
> Hope this will help you!

can i modify your code to fit in COCO 2014 val dataset?
