### ISSUE TITLE
all the values of APs are 0

### ISSUE THREAD

**Issue by StellaGAN** [amdegroot/ssd.pytorch#436]
1. How to test after training the model?python eval.py?
2.Why are my AP values in all categories zero?
3.What is the use of test.py?
4.When do you use trainval.txt &test.txt?

**Comment by StellaGAN** [comment]
>     1. to test after training the model?python eval.py?
>        2.Why are my AP values in all categories zero?
>        3.What is the use of test.py?
>        4.When do you use trainval.txt &test.txt?

**Comment by GuoxingYan** [comment]
请问你怎么解决的呢?
