### ISSUE TITLE
RGB vs BGR?

### ISSUE THREAD

**Issue by oarriaga** [amdegroot/ssd.pytorch#44]
Hello,
I was looking at your implementation and I believe the input to your model is an image with RGB ordering. I was also looking at the [keras implementation](https://github.com/rykov8/ssd_keras) and they use BGR values. I have been also testing with an [map evaluation script](https://github.com/oarriaga/single_shot_multibox_detector/blob/master/src/evaluate.py) and it seems that I get better results ;using the weights that you provided from the original caffe implementation, when I use BGR instead of RBG. Do you happen to know which order should we follow when using the original caffe weights?

Thank you very much :)

**Comment by alexkoltun** [comment]
It should be BGR, but currently the pretrained model was trained with RGB code so when using it an RGB input is expected, I am planning to contribute a pretrained model that was trained with BGR, then the inconsistency could be removed

**Comment by oarriaga** [comment]
Thank you @alexkoltun :)

**Comment by yxchng** [comment]
@alexkoltun how do you train with rgb when the vgg_fc_reduced weights from caffe is in bgr? Do you have a way to convert that to rgb or do you train the vgg_fc_reduced from scratch as well?

**Comment by xiaoyong** [comment]
Same question. Is the pretrained model (vgg16_fc_reducedfc.pth) in BGR or RGB order?
