### ISSUE TITLE
I can't achieve mAP (77.x)

### ISSUE THREAD

**Issue by lesonly** [amdegroot/ssd.pytorch#440]
I tried to run many times with different parameters. But I could not achieve the reported mAP (over 77%).

Almost mAP which I get are 71.x%.

Could you tell me how to set the training environment??

Thank you in advance.

**Comment by laisimiao** [comment]
@lesonly your mAP 71.x% that used pre-trained model or your own trained model?

**Comment by lesonly** [comment]
> @lesonly your mAP 71.x% that used pre-trained model or your own trained model?

Thank you for your reply! I use the weights of vgg16_reducedfc.pth，Does the pre-trained model mean the weight of vgg16?

**Comment by laisimiao** [comment]
i mean pre-trained model is ssd300_mAP_77.43_v2.pth this file and own trained model is using vgg16_reducedfc.pth to train from scratch

**Comment by laisimiao** [comment]
@lesonly i trained from scratch, but only get mAP about 0.45, and inference time is bigger than use ssd300_mAP_77.43_v2.pth to run eval.py
