### ISSUE TITLE
Happy New Year Everyone! Sorry,I got Low Map on coco

### ISSUE THREAD

**Issue by lesonly** [amdegroot/ssd.pytorch#453]
Happy New Year Everyone! I got a map = 0.04 on coco, I think it may be that I use the wrong code to generate the result file. Could you provide the code to generate the result file? This question has puzzled me for a long time. Thank you very much!

**Comment by immaping** [comment]
I got a map=0.009. And I don’t know what I should do¿ Have you solved that question¿
