### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/yxy/ssd.pytorch-master/data/coco/coco_labels.txt'

### ISSUE THREAD

**Issue by yangxiaoyany** [amdegroot/ssd.pytorch#454]
hello,  i want to train on 2007VOC dataset,so i don't  prepare the coco dataset.  So it occurs such errors.how  should i do? is it necessary to download coco dataset?

### No such file or directory: '/home/yxy/ssd.pytorch-master/data/coco/coco_labels.txt'

**Comment by huaibuhuai** [comment]
I also have the same question ,please help me save it

**Comment by ghost** [comment]
The same question.

**Comment by FoxerLee** [comment]
It's in the code's dictionary: https://github.com/amdegroot/ssd.pytorch/blob/master/data/coco_labels.txt
