### ISSUE TITLE
Error:TypeError: test_net() missing 6 required positional arguments:  'save_folder', 'net', 'cuda', 'dataset', 'transform', and 'top_k'

### ISSUE THREAD

**Issue by Jiahao-Lin7** [amdegroot/ssd.pytorch#461]
I am a newbie, when I using eval.py, It comes out the error:  'save_folder', 'net', 'cuda', 'dataset', 'transform', and 'top_k', I'm so comfused about this, can anyone help, thx.

**Comment by Yifei-Bi** [comment]
How did you solve this problem?

**Comment by lb1234564** [comment]
How did you solve this problem?
