### ISSUE TITLE
I want to transfer to MobileNet-SSD

### ISSUE THREAD

**Issue by skything** [amdegroot/ssd.pytorch#463]
As the titles,How I can do?

**Comment by skything** [comment]
Target [batchsize,48300,4] and Tensor[batchsize,2260,1] is not match

**Comment by nidengke** [comment]
> Target [batchsize,48300,4] and Tensor[batchsize,2260,1] is not match

please refer https://github.com/amdegroot/ssd.pytorch/issues/421

**Comment by skything** [comment]
> > Target [batchsize,48300,4] and Tensor[batchsize,2260,1] is not match
> 
> please refer #421

I was able to train this morning, but I made a mistake when using Eval to test. 
![image](https://user-images.githubusercontent.com/39761571/77883927-a65d1380-7296-11ea-9125-eddbbf4d9f4b.png)

**Comment by skything** [comment]
> > Target [batchsize,48300,4] and Tensor[batchsize,2260,1] is not match
> 
> please refer #421

Training is succeed...feature map is [19,10,5,3,2,1],I use the VOC2007 DATASETS

**Comment by skything** [comment]
@AtriSaxena

**Comment by skything** [comment]
@lzx1413

**Comment by skything** [comment]
@weidi1024

**Comment by skything** [comment]
![image](https://user-images.githubusercontent.com/39761571/78218157-e7039980-74ef-11ea-9198-3378ed67abb3.png)

**Comment by skything** [comment]
I GOT IT,AND CHANGE TO SMAE SHAPE.THAT MEANS IS  EXTRA-->[4,6,6,6,6,6] NOT AS [3,6,6,6,6,6]

**Comment by skything** [comment]
![image](https://user-images.githubusercontent.com/39761571/78256707-7bd7b880-752b-11ea-8b1c-e05bed2f7387.png)
I am a student,that is my first time by pytorch.
