### ISSUE TITLE
Any scheduled time to support image size 512?

### ISSUE THREAD

**Issue by shwoo93** [amdegroot/ssd.pytorch#49]
Hello

Firstly I really appreciate your work.
I wonder if you have in mind to support image size 512 soon. 

Thanks

**Comment by amdegroot** [comment]
I hope to start working on that in the next few days, as I should have a little bit of time.  I will probably be able to give you a more accurate time frame after I start working on it though, and since this is all done in my free-time I can't guarantee anything, but hopefully in the next couple weeks!  I want to knock out all of the additional features on this network so I can get going on DSSD.  If you want to help though or have any code that you've worked on, as always feel free to submit a PR.

**Comment by lopuhin** [comment]
Hi, has anyone tried to implement SSD 512? Is it a matter of specifying the correct config, or some other changes are required?

**Comment by lopuhin** [comment]
Hopefully I implemented SSD 512 in https://github.com/lopuhin/ssd.pytorch/commit/600e7112461247ed3a5b3a01b8792eeddd558f6b https://github.com/lopuhin/ssd.pytorch/commit/cfa226c797f4c80a3bc18a76f8213d9948fe3708 and https://github.com/lopuhin/ssd.pytorch/commit/3be5e7fb825bd28157ab360b24ac5663fa4bd0c6

**Comment by amdegroot** [comment]
@lopuhin Any chance you'd be willing to put out a PR including the 512 implementation? Thanks for implementing it!

**Comment by lopuhin** [comment]
@amdegroot sure, it would be awesome! I also moved code around a bit to make it pip-installable, I hope this is ok? Right now it needs a couple of fixes to make it ready for PR - bring back pytorch 0.2.0 support and fix VOC training example, I hope I'll be able to fix this issues in the next few weeks.

**Comment by qijiezhao** [comment]
@lopuhin 
Hi, I copied your code from your ssd.pytorch and has tried to reproduce the result. However,  after setting every parameters, the out=net(images) in train.py can not move forward any more. This leads to training difficulties, could you help me out? any advice? thank you.

**Comment by ghost** [comment]
> Hopefully I implemented SSD 512 in [lopuhin@600e711](https://github.com/lopuhin/ssd.pytorch/commit/600e7112461247ed3a5b3a01b8792eeddd558f6b) [lopuhin@cfa226c](https://github.com/lopuhin/ssd.pytorch/commit/cfa226c797f4c80a3bc18a76f8213d9948fe3708) and [lopuhin@3be5e7f](https://github.com/lopuhin/ssd.pytorch/commit/3be5e7fb825bd28157ab360b24ac5663fa4bd0c6)

I can’t even believe that the 512 input size can be rebuilt so easily.
