### ISSUE TITLE
can you provide a high resolution image for ssd.png

### ISSUE THREAD

**Issue by gaopeng-eugene** [amdegroot/ssd.pytorch#5]

**Comment by amdegroot** [comment]
I'll try to provide a higher res version. GitHub wouldn't let me upload the original so I had to downsize it.  You can also easily reproduce it as shown (here)[https://github.com/szagoruyko/functional-zoo]

**Comment by amdegroot** [comment]
Now that I have updated the model, the method shown above seems to not work.  I will be working on this when I get around to creating a functional model definition for the repo I linked above and will post a link to it when I get to it, but GitHub will not let me post a higher res image to the ReadMe.  I apologize for that.
