### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by namihagi** [amdegroot/ssd.pytorch#507]
I tried some versions, but failed to train.
And I cant find information of enviroment in README.md.

which pytorch version do you use?
thank you!

**Comment by dikshaaswal** [comment]
Same problem with me.
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
Such error occured

**Comment by namihagi** [comment]
I solved this problem myself.

I trained on the following environment.
Python 3.6
CUDA 10.0
Pytorch 1.0.0

I used the docker image, pytorch/pytorch:1.0-cuda10.0-cudnn7-devel.
And, I installed opencv-python, opencv-contrib-python and pycocotools by pip.
Finally, to follow this [link](https://github.com/amdegroot/ssd.pytorch/issues/173#issuecomment-476459069), I changed some codes.
