### ISSUE TITLE
How to visualize the computational graph?

### ISSUE THREAD

**Issue by aymenx17** [amdegroot/ssd.pytorch#52]
I saw the images that represent the graph, but they were blurred. Are there some ways or scripts  to reproduce the graph during training and inference?  In the file .gitignore it seems it was used visualize.py to generate those pictures. I need this because i think it helps a lot as a first step for a good understanding of the architecture and the functionality of the model itself.

**Comment by amdegroot** [comment]
Hi! I agree and weirdly I can't get the script to work anymore.  If you would like to mess with it however, you can find it [here](https://github.com/szagoruyko/functional-zoo/blob/master/visualize.py).  If you can get it to work, feel free to send a PR as that would be a really nice feature to have.
