### ISSUE TITLE
Cannot implement Eval.py file because of TypeError: forward() missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by chiehpower** [amdegroot/ssd.pytorch#528]
After I finished the training, I wanna evaluate the results by my trained model. 
However, when the first time ran the script, it happened this error. 
```
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```
So I add a `@staticmethod` above the def forward. 
Ran again, and then I got this error below:
```
Finished loading model!
2007
Traceback (most recent call last):
  File "eval.py", line 440, in <module>
    thresh=args.confidence_threshold)
  File "eval.py", line 387, in test_net
    detections = net(x).data
  File "C:\Users\chiehpower\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```

I thought it was a known issue? However, I cannot find a proper solution for this case...
Is there anyone who can provide or share some suggestions? 
Thank you so much!!!

BR,
Chieh

# Version
torch: 1.6.0 
cuda: 10.2
OS: WIN10

**Comment by chiehpower** [comment]
The problem was solved by low pytorch version.

Solved by
```
pip install torch==1.3.1 -f https://download.pytorch.org/whl/torch_stable.html
pip install torchvision==0.4.1
```

**Comment by wj-shin** [comment]
> The problem was solved by low pytorch version.
> 
> Solved by
> 
> ```
> pip install torch==1.3.1 -f https://download.pytorch.org/whl/torch_stable.html
> pip install torchvision==0.4.1
> ```

I have a problem also when I install pytorch 1.3
