### ISSUE TITLE
running eval.py on my dataset gets low map

### ISSUE THREAD

**Issue by KingofLong** [amdegroot/ssd.pytorch#531]
I trained my dataset (in VOC format) for 100000 its, and got a low loss, but I can only get a 0.09 ap best for my classes in eval. Is it the problem that I named my label from 0 to 7 in <name> of .xml?
I used VOC.pth for evaluation, changed voc0712.py to suit my dataset and trained twice but only get same result.

**Comment by KingofLong** [comment]
Find the issue, the weight of the net didnt update.

**Comment by Hrqingqing** [comment]
> Find the issue, the weight of the net didnt update.

Hello，I have the same problem，and you said the weight of the net didnt update，so I wan't to know how to do it.Thank you.

**Comment by yjg123456** [comment]
> > Find the issue, the weight of the net didnt update.
> 
> Hello，I have the same problem，and you said the weight of the net didnt update，so I wan't to know how to do it.Thank you.

same here
