### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by KeepFaithMe** [amdegroot/ssd.pytorch#541]
File "F:\Target Detection Source Code\ssd\layers\modules\multibox_loss.py", line 97, in forward
    loss_c[pos] = 0  # filter out pos boxes for now
IndexError: The shape of the mask [32, 8732] at index 0 does not match the shape of the indexed tensor [279424, 1] at index 0
How to solve this problem?

**Comment by minji-o-j** [comment]
How did you solve it?

**Comment by samra-irshad** [comment]
Facing same issue, did you manage to resolve it?

**Comment by minji-o-j** [comment]
@samra-irshad 
I fixed it by referring to the issue board of this repository.

https://github.com/amdegroot/ssd.pytorch/issues/421#issuecomment-545861899

**Comment by bspivey** [comment]
I'm having the same issue too.

**Comment by uzair789** [comment]
#518
