### ISSUE TITLE
RunTime Error in Training with default values

### ISSUE THREAD

**Issue by chauhan-utk** [amdegroot/ssd.pytorch#56]
`python train.py 
Loading base network...
Initializing weights...
Loading Dataset...
Training SSD on VOC0712
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    train()
  File "train.py", line 181, in train
    out = net(images)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 70, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/gpu/utkrsh/code/ssd.pytorch/ssd.py", line 76, in forward
    s = self.L2Norm(x)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/gpu/utkrsh/code/ssd.pytorch/layers/modules/l2norm.py", line 21, in forward
    x/=norm.expand_as(x)
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/variable.py", line 725, in expand_as
    return Expand.apply(self, (tensor.size(),))
  File "/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 111, in forward
    result = i.expand(*new_size)
RuntimeError: The expanded size of the tensor (512) must match the existing size (8) at non-singleton dimension 1. at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generic/T$CTensor.c:323
`

I am getting the above stack trace after running train.py for default values. The dataset and weights were downloaded in the default location.
I am using python 3.6 and pytorch 0.2.0
I do understand the meaning of the error, I am just not able to find the source. Can anyone point in the right direction?

**Comment by amdegroot** [comment]
Do you have the latest version of the repo?  That's the error I was getting about a week ago before I updated it for pytorch 0.2.0.

**Comment by amdegroot** [comment]
Yeah I recently updated line 20 and 21, which were the sources of the error since the functionality of `.sum()` changed to assume `keep dim = False`, by default.  If you do a git pull it should be fine.

**Comment by chauhan-utk** [comment]
@amdegroot Thanks! It was the issue. Training started with this deprecation warning:
`/users/gpu/utkrsh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py:450: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.`

I got an error after a few iterations:
`THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generated/../THCReduceAll.cuh line=334 error=77 : an illegal memory access was encountered`
`RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1502009910772/work/torch/lib/THC/generated/../THCReduceAll.cuh:334`

Did you had this error when training on the updated code?
[Here](https://github.com/torch/cutorch/issues/489) is one similar issue. Looks like the code needs to be updated or I am missing something simple here also. I will try to make it work, otherwise open a new issue.

**Comment by amdegroot** [comment]
Hm.. Did you do a git pull or did you just fix those two lines? Because there were some other issues as well that weren't up to date that I had to fix, but I ran through a full 120k iterations last week after I updated everything without any errors.  Let me know if you find anything, I'll look into it as well.

**Comment by chauhan-utk** [comment]
I did a git pull.  Got this summary: `9 files changed, 66 insertions(+), 51 deletions(-)`

**Comment by amdegroot** [comment]
Alright, yeah I'm unsure. What is your batch size? I think training with a batch size of 16 may lead to NaNs, but that could be a different problem. I'll look into it after work, but please let me know if you find anything

**Comment by chauhan-utk** [comment]
`batch_size=32` works fine. I was getting the previous error after 50 iterations, even after multiple runs. Please update this in `train.py`. Thanks a lot for help.

**Comment by insomnia250** [comment]
I also encounter this problem with parameter` batch_size=16` as default and with three 1080 Ti for training.  After changing to 32 ,it works fine by now. But I don't know why this happens. So have you figure it out? 
Thanks.

**Comment by bestlin** [comment]
I have the same issue. Has anyone fixed this?

**Comment by lovekesh-thakur** [comment]
Same here. Made a new git pull as suggested but getting same error.

**Comment by vijinkp** [comment]
Im facing the same error. Anyone fixed?

**Comment by usherbob** [comment]
When I tried to use two GPUs, this error just disappeared.

**Comment by chuzcjoe** [comment]
> Yeah I recently updated line 20 and 21, which were the sources of the error since the functionality of `.sum()` changed to assume `keep dim = False`, by default. If you do a git pull it should be fine.

Hi, i recently had the same issue. Where did you update your line 20 and 21?
