### ISSUE TITLE
in your README you talked about the version 2 of SSD

### ISSUE THREAD

**Issue by gaopeng-eugene** [amdegroot/ssd.pytorch#6]
where can I find the SSD version2 paper.

**Comment by ellisbrown** [comment]
The original version of the paper can be found [here](https://arxiv.org/abs/1512.02325v1).
The newest version of the paper can be found [here](https://arxiv.org/abs/1512.02325).

We originally did not realize there was a newer version of the paper than the original, and thus had set out using solely the original version.  When we realized there was an updated version ("V2" on the readme), we naturally switched over and focused on the newer & better version.  Down the road, we intend to remove reference to the original version in favor of the newer one.

**Comment by yxchng** [comment]
@ellisbrown I can't find the newer version in the caffe ssd code. Is it that the author only publish the paper but never update the code?

**Comment by amdegroot** [comment]
Currently the caffe code only shows the newest version.  If you go back through his commit history you can find the older version.
