### ISSUE TITLE
Possible bug for the `Resize` class in augmentations.py

### ISSUE THREAD

**Issue by crazylyf** [amdegroot/ssd.pytorch#61]
Hi all,

When image is resized, bounding boxes should be scaled accordingly, but the `Resize` class in `augmentations.py` does not scale the bounding box. Is this a bug?

**Comment by lzx1413** [comment]
Because ToPercentCoords() is applied before resize.

**Comment by crazylyf** [comment]
oh, I see. thanks @lzx1413
