### ISSUE TITLE
MultiBoxLoss error

### ISSUE THREAD

**Issue by dgmadalin** [amdegroot/ssd.pytorch#69]
I am trying to modify the code for a different number of classes(positive / negative). I think there is some problem in multibox_los.py at 

        # Compute max conf across batch for hard negative mining
        batch_conf = conf_data.view(-1, self.num_classes)

        loss_c = log_sum_exp(batch_conf) - batch_conf.gather(1, conf_t.view(-1, 1))

        # Hard Negative Mining
        loss_c[pos] = 0  # filter out pos boxes for now
        loss_c = loss_c.view(num, -1)
        _, loss_idx = loss_c.sort(1, descending=True)
        _, idx_rank = loss_idx.sort(1)

In my case loss_c has 16000x1 (16 images in a batch each with 1000 elements)
pos has a shape of 16x1000.  What's the point of sorting according dimension 1 ?

**Comment by niaoyu** [comment]
see https://github.com/amdegroot/ssd.pytorch/issues/99
