### ISSUE TITLE
In detection L47, is it typo?

### ISSUE THREAD

**Issue by jeong-tae** [amdegroot/ssd.pytorch#79]
I was looking your code to reference, and i found out the code doesn't work at 47

https://github.com/amdegroot/ssd.pytorch/blob/master/layers/functions/detection.py#L47
47: self.output.expand_(num, self.num_classes, self.top_k, 5)

i got AttributeError: 'torch.FloatTensor' object has no attribute 'expand_' error
is it intended or typo? i think 'expand_' should be 'expand'

if anyone didn't get this error, maybe my pytorch version has problem(0.2.0_4 version)

**Comment by AndrewZhao** [comment]
0.2.0.post3 has no problem.
