### ISSUE TITLE
Not use RandomHorizontalFlip?

### ISSUE THREAD

**Issue by miraclebiu** [amdegroot/ssd.pytorch#8]
The train_transform() is not used in the base_transform. So does this project use  RandomHorizontalFlip?
Or this function is called other place?

**Comment by amdegroot** [comment]
Hi, 
The complete data augmentation is undergo in the augmentation branch and is very close to completion, it just needs to be tested (I have been caught up with other work or it would already be done). However, random horizontal flip is not used anywhere else, so until that is merged with master we just apply the base transforms.

**Comment by amdegroot** [comment]
According to the paper, the data augmentation should only add ~3 - 5% to the mAP though.

**Comment by miraclebiu** [comment]
Thanks!
