### ISSUE TITLE
seem works for VOC datasets

### ISSUE THREAD

**Issue by taokong** [amdegroot/ssd.pytorch#83]
The code works well for VOC dataset, and I get 77.5 mAP. Now I'm trying SSD512

**Comment by taokong** [comment]
79.1 mAP with SSD512

**Comment by AndrewZhao** [comment]
hello，did you use the voc difficult dataset?

**Comment by guantinglin** [comment]
Hi, @taokong 
 Can you share the configuration of your experiments? 
 In this repo, I can only reach the mAP of around 73% in the default setting.

**Comment by guantinglin** [comment]
@taokong 
For example. 
What's your batch size, number of gpus, iterations...

**Comment by taokong** [comment]
batchsize=32 for SSD300 and 20 for SSD512, using 4 gpus
