### ISSUE TITLE
The implementation of nms seems wrong.

### ISSUE THREAD

**Issue by qfgaohao** [amdegroot/ssd.pytorch#86]
The implementation of nms in [layers/box_utils.py](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/box_utils.py#L173) picks the top-k scores and the corresponding boxes, and then filter by IOU among the above boxes. Therefore nms is only applied to the corresponding boxes of the top-k scores in the code. However, the normal implementation filters among boxes and returns the top-k boxes with biggest scores and IOU less than the threshold.

**Comment by gurkirt** [comment]
I practice it wouldn't make much difference.

**Comment by qfgaohao** [comment]
Good to know! Thanks @gurkirt !

**Comment by qfgaohao** [comment]
Good to know! Thanks @gurkirt !
