### ISSUE TITLE
Different numbers of default boxes between priobox and prediction?

### ISSUE THREAD

**Issue by MinLiAmoy** [amdegroot/ssd.pytorch#94]
Hi,
I started reading the codes recently and I am confused about the number of default bounding boxes.
In prior_box.py, 6 default boxes are generated per feature map location. However, [4, 6, 6, 6, 4, 4] boxes are selected from different scales.
I guess I missed some implementation details and where are they manipulated to be the same?
Thanks!

**Comment by MinLiAmoy** [comment]
Oh, in multibox_loss.py, priors = priors[:loc_data.size(1), :] which indeed make the number of  default bbox equal to the predicitions. However, the outputs of PriorBox are arraged by different scales, and just slicing the tensor of priors boxes seems wrong. Is it a bug?
Thanks!

**Comment by IssacCyj** [comment]
@MinLiAmoy loc_data.size(1) = 8732 according to original settings and it has included different aspect ratios within. I think no problem here.

**Comment by IssacCyj** [comment]
@MinLiAmoy 
> In prior_box.py, 6 default boxes are generated per feature map location
Could you point out the line number? Indeed, there are some bugs in the code and I haven't noticed this one yet.

**Comment by IssacCyj** [comment]
@MinLiAmoy

> In prior_box.py, 6 default boxes are generated per feature map location

Could you point out the line number? Indeed, there are some bugs in the code and I haven't noticed this one yet.

**Comment by amdegroot** [comment]
To address the original question, as the paper mentions: "For conv4_3, conv10_2 and conv11_2, we only associate 4 default boxes at each feature map location – omitting aspect ratios of 1/3 and 3. For all other layers, we put 6 default boxes as described in Sec. 2.2".  

In the same way, [4, 6, 6, 6, 4, 4] refers to the number of boxes associated at each feature map location.  You can read more about it in the original [paper](https://arxiv.org/abs/1512.02325).  Let me know if that doesn't clear it up.

**Comment by YuliangXiu** [comment]
I test torch.sum(priors[:half,:]-priors[half:,:]) == 0, the result is true. So on multi-gpu model, the priors are concatenated as whole by GPU inference order.
