### ISSUE TITLE
In multibox_loss you only consider one default box for each ground truth

### ISSUE THREAD

**Issue by ASoleimaniB** [amdegroot/ssd.pytorch#95]
Hi,

In SSD paper, we see that one or **More than one** default boxes are assigned to each groundtruth. Therefore, in localization loss (loc) we are trying to calculate error for one or More than one default boxes per object. However, in **multibox_loss** code the loss is calculate for only the best matched default box for the ground truth box. Am I right?
**loss_l = F.smooth_l1_loss(loc_p, loc_t, size_average=False)**
You can see what I am explaining by the sizes of **loc_p** and **loc_t**

Does the official code in caffee do the same process and neglect what they say in the paper?

**Comment by IssacCyj** [comment]
@ASoleimaniB I think the parameter overlap_thresh in multibox_loss.py is the threshold above which a default box is counted as a positive one. I find that the size of loc_p and loc_t is [m, 4] where m is around several hundreds(like I have 354, 473, etc.).

line 82 in multibox_loss.py :
`        pos = conf_t > 0
        num_pos = pos.sum(dim=1, keepdim=True)`

and the definition of match() in box_utils.py
`    conf[best_truth_overlap < threshold] = 0  # label as background
`
can account for this, right?

**Comment by ASoleimaniB** [comment]
You are right and I was wrong.
Thank you for your response
