### ISSUE TITLE
Priors not matched at all in MultiBoxLoss?

### ISSUE THREAD

**Issue by harpone** [amdegroot/ssd.pytorch#97]
The issue starts on line 65 in `multibox_loss.py`:
```
        # match priors (default boxes) and ground truth boxes
        loc_t = torch.Tensor(num, num_priors, 4)
        conf_t = torch.LongTensor(num, num_priors)
        for idx in range(num):
            truths = targets[idx][:, :-1].data
            labels = targets[idx][:, -1].data
            defaults = priors.data
            match(self.threshold, truths, defaults, self.variance, labels,
                  loc_t, conf_t, idx)
```

**Since `loc_t` and `conf_t` are torch tensors, just calling the function match() does actually nothing.**

I guess the idea was to wrap them into `Variable`s before running the match function and actually updating the `Variable().data` inside the `match` function?

**Comment by IssacCyj** [comment]
Hi, I just did a little experiment and find it works for tensors and numpy arrays but not sth like integers. I'm not sure how it works but it should work here.

**Comment by harpone** [comment]
Ah I guess I was confused... match does change the tensor values, since there's `loc_t[idx] = ...` inside... I just observed something weird (the values were not changing).
